version: "3"
services:
  postgres_sorteador_db:
    image: postgres:14
    container_name: postgres_sorteador_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - ./back-end/.env.test
    volumes:
      - pg_sorteador-db:/var/lib/postgresql/data

  node_sorteador_app_test:
    container_name: node_sorteador_app
    build: ./back-end
    image: node_sorteador_app_test_image
    ports:
      - 5000:5000
    depends_on:
      - postgres_sorteador_db
    env_file:
      - ./back-end/.env.test

  app_react:
    build: ./front-end
    container_name: react_front
    image: app_react_image
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_sorteador_db
      - node_sorteador_app_test
      - app_react

volumes:
  build_react:
  pg_sorteador-db:
